### ISSUE TITLE
List of experts

### ISSUE THREAD

**Issue by eucalypto** [eucalypto/march-twenty-squared#1]
In order to have an overview over all experts, as a viewer I want to see a list of them with basic information.

Each expert should have these basic information:
- first name
- last name
- email
- phone

This list should be scrollable.

---
Sub-tasks:
- [x] #3 Design view of one expert list item
- [x] #2 Create basic RecyclerView
- [x] #4 Create data class and link to Recyclerview
