### ISSUE TITLE
Firebase Setup

### ISSUE THREAD

**Issue by eucalypto** [eucalypto/march-twenty-squared#12]
In order to show dynamic content
as a developer
I want to have Firebase set-up

**Comment by eucalypto** [comment]
# Sub-tasks
- [x] Set up Firebase project via web page
- [x] Import configuration & libraries into Android project for this Firebase project 
- [x] Set up security rules for this Firebase project

# Firebase Online Setup
[Documentation](https://firebase.google.com/docs/firestore/security/rules-structure)
[Documentation: best practice for security rules](https://firebase.google.com/docs/firestore/security/insecure-rules)

# Firebase setup in Android Studio
Just follow this guide:
https://firebase.google.com/docs/android/setup

**Comment by eucalypto** [comment]
Since this is an open source project, I need to make sure the database is secure. How are the users going to access it? Do they need write permissions?

So far, the app just fetches data from the database. So it needs only read permissions so far. This should be easy enough.
